name: Android Debug APK

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android platform & build-tools (tollerante)
        run: |
          sdkmanager "platform-tools" "platforms;android-34" || true
          sdkmanager "build-tools;35.0.0" || true
          sdkmanager "build-tools;34.0.2" || true
          sdkmanager "build-tools;34.0.0" || true
          sdkmanager "cmdline-tools;latest" || true

      - name: Ensure Android project exists (first time)
        run: flutter create . --platforms=android

      - name: Ensure gradle.properties (AndroidX + memoria)
        run: |
          mkdir -p android
          mkdir -p android/app
          GP=android/gradle.properties
          touch "$GP"
          grep -q "android.useAndroidX" "$GP" || echo "android.useAndroidX=true" >> "$GP"
          grep -q "android.enableJetifier" "$GP" || echo "android.enableJetifier=true" >> "$GP"
          grep -q "org.gradle.jvmargs" "$GP" || echo "org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8" >> "$GP"

      - name: Patch minSdkVersion=21 (per plugin tipo sqflite)
        run: |
          if [ -f android/app/build.gradle ]; then
            sed -i 's/minSdkVersion *[0-9][0-9]*/minSdkVersion 21/g' android/app/build.gradle || true
          fi

      - name: Ensure lib/main.dart exists (fallback)
        run: |
          if [ ! -f lib/main.dart ]; then
            mkdir -p lib
            cat > lib/main.dart <<'EOF'
            import 'package:flutter/material.dart';
            void main() => runApp(const MaterialApp(home: Scaffold(body: Center(child: Text('All-in-One v5')))));
            EOF
          fi

      - name: Flutter doctor (diagnostica)
        run: flutter doctor -v

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (debug, verbose)
        run: flutter build apk --debug --verbose

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

