name: Android Debug APK

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android platform & build-tools
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Ensure Android project exists (first time)
        run: flutter create . --platforms=android

      - name: Ensure lib/main.dart exists (fallback)
        run: |
          if [ ! -f lib/main.dart ]; then
            mkdir -p lib
            cat > lib/main.dart <<'EOF'
            import 'package:flutter/material.dart';
            void main() => runApp(const MaterialApp(home: Scaffold(body: Center(child: Text('All-in-One v5')))));
            EOF
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
